name: care
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0' # Updated for broader compatibility

dependencies:
  flutter:
    sdk: flutter

  intl: ^0.19.0
  hive: ^2.2.3            # NEW: Core Hive database library
  hive_flutter: ^1.1.0    # NEW: Flutter helpers for Hive
  carousel_slider: ^5.1.1
  flutter_map: ^8.2.1
  latlong2: ^0.9.1
  geolocator: ^14.0.2
  permission_handler: ^12.0.1
  flutter_polyline_points: ^3.0.1
  table_calendar: ^3.1.3
  http: ^1.5.0
  fl_chart: ^0.68.0
  cached_network_image: ^3.3.0
  url_launcher: ^6.2.6     # to call ambulance number (108) or driver phone number
  shared_preferences: ^2.2.2  # to store login/session and implement logout
  razorpay_flutter: ^1.3.7   # or flutter_stripe / pay for online payments
  flutter_svg: ^2.2.1
  syncfusion_flutter_charts: ^20.4.48
  flutter_chat_ui: ^1.6.0
  flutter_dotenv: ^5.0.2  # For API key security
  flutter_chat_types: ^3.6.2
  uuid: ^4.5.1
  iconsax: ^0.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0 # Updated to a recent version
  

  # --- NEW DEV DEPENDENCIES ---
  # These are needed to auto-generate code for your models.
  hive_generator: ^2.0.1
  build_runner: ^2.4.7

flutter:
  uses-material-design: true
  assets:
    - .env
    

scripts:
  build: flutter pub run build_runner build --delete-conflicting-outputs
  watch: flutter pub run build_runner watch
